stages:
  - lint

ansible_lint:
  stage: lint
  image: python:3.9  # Using Python image as an example
  before_script:
    - pip install ansible-lint  # Install Ansible Lint
  script:
    - ansible-lint playbook.yml  # Lint an example playbook

stages:
  - deploy

deploy_to_production:
  stage: deploy
  script:
    - ansible-playbook -i inventory site.yml --tags "baseline" --extra-vars local_password=${local_password} local_user=${local_user}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: false
  environment:
    name: production
    url: https://yourproduction.environment.url

