---
ansible_user: "{{ vault_ansible_user }}"
ansible_password: "{{ vault_ansible_password }}"
ansible_become: yes
ansible_become_method: enable
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
