---
# Junos Template Baseline 
- name: Create configurtion file
  block:

    - name: Creating Junos template from roles/networkBaseline/templates/junos_config.j2
      ansible.builtin.template:
        src: roles/networkBaseline/templates/junos_config.j2
        dest: "{{ item }}"
        mode: "0644"
      delegate_to: localhost
      loop:
        - roles/networkBaseline/staging/{{ cfg_filename }}
        - roles/networkBaseline/backups/staged/{{ datetime }}/{{ cfg_filename }}
  tags:
    - build
    - deploy
