---
# Cisco NX-OS Baseline 
- name: Create configurtion file
  block:
 
    - name: Creating NX-OS template from /roles/networkBaseline/templates/nxos_config.j2
      ansible.builtin.template:
        src: roles/networkBaseline/templates/nxos_config.j2
        dest: "{{ item }}"
      delegate_to: localhost
      loop:
        - roles/networkBaseline/staging/{{ cfg_filename }}
        - roles/networkBaseline/backups/{{ datetime }}/{{ cfg_filename }}
  tags:
    - build
    - deploy
